export const students = [
  {
    id: 1,
    name: "Ali Khan",
    age: 21,
    email: "ali.khan@example.com",
    course: "Web Development",
    level: "Intermediate",
    progress: 75,
  },
  {
    id: 2,
    name: "Sara Ahmed",
    age: 22,
    email: "sara.ahmed@example.com",
    course: "Generative AI",
    level: "Beginner",
    progress: 45,
  },
  {
    id: 3,
    name: "Usman Malik",
    age: 24,
    email: "usman.malik@example.com",
    course: "React.js",
    level: "Advanced",
    progress: 90,
  },
  {
    id: 4,
    name: "Ayesha Noor",
    age: 20,
    email: "ayesha.noor@example.com",
    course: "JavaScript",
    level: "Intermediate",
    progress: 68,
  },
  {
    id: 5,
    name: "Hamza Shah",
    age: 23,
    email: "hamza.shah@example.com",
    course: "Node.js",
    level: "Beginner",
    progress: 35,
  },
  {
    id: 6,
    name: "Fatima Ali",
    age: 21,
    email: "fatima.ali@example.com",
    course: "Python",
    level: "Intermediate",
    progress: 72,
  },
  {
    id: 7,
    name: "Bilal Ahmed",
    age: 25,
    email: "bilal.ahmed@example.com",
    course: "Full Stack Development",
    level: "Advanced",
    progress: 88,
  },
  {
    id: 8,
    name: "Zainab Khan",
    age: 22,
    email: "zainab.khan@example.com",
    course: "AI Engineering",
    level: "Beginner",
    progress: 40,
  },
];